name: Pull request
run-name: Pull request 🚀
on: [pull_request]
jobs:
  Install-Deps:
    runs-on: ubuntu-latest
    concurrency:
      group: monorepo-test-suites-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v3
        name: Pull repo
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        name: Setup Node.js
        with:
          node-version: 18.12
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

