name: Pull request
run-name: Pull request 🚀
on: [pull_request]
jobs:
  nx:
    name: Nx Affected
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [build, test, lint]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - uses: nrwl/nx-set-shas@v3
        name: Setup Nx base and head
      - name: Npm install
        run: npm i
      - run: npx nx affected --target=${{ matrix.target }} --parallel=3

